# docker-compose.yml (Updated for Local Node.js Development)
version: "3.8"

services:
  db:
    image: postgres:15-alpine # Or your preferred Postgres version
    container_name: food_delivery_db_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # Reads from your .env file
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432" # Expose DB port to your localhost
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data

volumes:
  postgres_data: # Define the named volume

# Optional: You can keep the network if you plan other services,
# but it's not strictly needed if only the DB runs in Docker.
# networks:
#   food_delivery_net:
#     driver: bridge
